#!/usr/bin/env python3
"""Render deterministic Markdown and Mermaid architecture description views."""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path
from typing import Any

import yaml


GENERATED_MARKER = "<!-- GENERATED BY govern-modular-event-architecture; DO NOT EDIT -->"


LABELS = {
    "zh": {
        "architecture": "架構導覽",
        "system": "系統總覽",
        "parents": "Parent Views",
        "flows": "端到端 Flows",
        "modules": "模組",
        "purpose": "目的",
        "parent": "父模組",
        "status": "實作狀態",
        "inputs": "輸入 Ports",
        "outputs": "輸出 Ports",
        "events": "輸出 Events",
        "state": "擁有狀態",
        "effects": "副作用",
        "errors": "異常",
        "invariants": "不變條件",
        "entrypoints": "程式入口",
        "contracts": "公開 Symbols",
        "ports": "Port 契約",
        "event_contracts": "Event 契約",
        "structure": "結構圖",
        "flow_diagram": "Flow 圖",
        "steps": "執行步驟",
        "success": "成功結果",
        "none": "無",
    },
    "en": {
        "architecture": "Architecture Guide",
        "system": "System Overview",
        "parents": "Parent Views",
        "flows": "End-to-End Flows",
        "modules": "Modules",
        "purpose": "Purpose",
        "parent": "Parent",
        "status": "Implementation Status",
        "inputs": "Input Ports",
        "outputs": "Output Ports",
        "events": "Emitted Events",
        "state": "Owned State",
        "effects": "Side Effects",
        "errors": "Errors",
        "invariants": "Invariants",
        "entrypoints": "Entrypoints",
        "contracts": "Public Symbols",
        "ports": "Port Contracts",
        "event_contracts": "Event Contracts",
        "structure": "Structure",
        "flow_diagram": "Flow Diagram",
        "steps": "Ordered Steps",
        "success": "Success",
        "none": "None",
    },
}


def load_manifest(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    if not isinstance(data, dict):
        raise ValueError("manifest root must be a mapping")
    if data.get("schema_version") != "1.1.0":
        raise ValueError("description views require schema_version 1.1.0")
    return data


def _labels(manifest: dict[str, Any]) -> dict[str, str]:
    language = str(manifest.get("project", {}).get("documentation_language", "zh-TW")).lower()
    return LABELS["zh" if language.startswith("zh") else "en"]


def _escape(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _mermaid_label(value: Any) -> str:
    return str(value).replace('"', "'").replace("\n", " ")


def _node_id(value: str) -> str:
    return "n_" + re.sub(r"[^A-Za-z0-9_]", "_", value)


def _file_name(module_id: str) -> str:
    return module_id + ".md"


def _list_text(values: list[Any], none_label: str) -> str:
    return ", ".join(f"`{_escape(item)}`" for item in values) if values else none_label


def _module_table(modules: list[dict[str, Any]], labels: dict[str, str]) -> list[str]:
    lines = [
        f"| ID | Level | Role | {labels['parent']} | {labels['status']} | {labels['purpose']} |",
        "|---|---|---|---|---|---|",
    ]
    for module in modules:
        purpose = module.get("description", {}).get("purpose", "")
        lines.append(
            f"| `{module.get('id')}` | {module.get('level')} | {module.get('role')} | "
            f"`{module.get('parent') or '-'}` | {module.get('implementation_status')} | {_escape(purpose)} |"
        )
    return lines


def _structure_diagram(modules: list[dict[str, Any]], include_dependencies: bool = True) -> list[str]:
    lines = ["```mermaid", "flowchart TD"]
    known = {str(module.get("id")) for module in modules}
    for module in modules:
        module_id = str(module.get("id"))
        label = f"{module_id} ({module.get('level')})"
        lines.append(f'    {_node_id(module_id)}["{_mermaid_label(label)}"]')
    for module in modules:
        module_id = str(module.get("id"))
        parent = module.get("parent")
        if parent in known:
            lines.append(f"    {_node_id(str(parent))} -->|owns| {_node_id(module_id)}")
        if include_dependencies:
            for target in module.get("depends_on", []):
                if target in known:
                    lines.append(f"    {_node_id(module_id)} -.->|depends| {_node_id(str(target))}")
    lines.append("```")
    return lines


def _code_links(entries: list[dict[str, Any]], prefix: str, none_label: str) -> str:
    if not entries:
        return none_label
    values = []
    for entry in entries:
        path = str(entry.get("path", ""))
        symbol = str(entry.get("symbol", ""))
        kind = str(entry.get("kind", ""))
        values.append(f"[`{symbol}`]({prefix}{path}) ({kind})")
    return "<br>".join(values)


def _module_card(module: dict[str, Any], labels: dict[str, str], prefix: str) -> list[str]:
    description = module.get("description", {})
    none = labels["none"]
    lines = [f"### `{module.get('id')}`", ""]
    lines.extend(
        [
            f"- **{labels['purpose']}:** {_escape(description.get('purpose', ''))}",
            f"- **{labels['parent']}:** `{module.get('parent') or '-'}`",
            f"- **{labels['status']}:** `{module.get('implementation_status')}`",
            f"- **{labels['inputs']}:** {_list_text(description.get('input_ports', []), none)}",
            f"- **{labels['outputs']}:** {_list_text(description.get('output_ports', []), none)}",
            f"- **{labels['events']}:** {_list_text(description.get('emitted_events', []), none)}",
        ]
    )
    states = description.get("owned_state", [])
    lines.append(
        f"- **{labels['state']}:** "
        + ("; ".join(f"`{_escape(item.get('name'))}` — {_escape(item.get('description'))}" for item in states) if states else none)
    )
    effects = description.get("side_effects", [])
    lines.append(
        f"- **{labels['effects']}:** "
        + ("; ".join(f"{_escape(item.get('description'))} (`{_escape(item.get('via_port', '-'))}`)" for item in effects) if effects else none)
    )
    errors = description.get("errors", [])
    lines.append(
        f"- **{labels['errors']}:** "
        + ("; ".join(f"`{_escape(item.get('id'))}`: {_escape(item.get('condition'))} → `{_escape(item.get('event'))}` → {_escape(item.get('handling'))}" for item in errors) if errors else none)
    )
    lines.append(f"- **{labels['invariants']}:** " + ("; ".join(_escape(item) for item in description.get("invariants", [])) or none))
    lines.append(f"- **{labels['entrypoints']}:** {_code_links(module.get('entrypoints', []), prefix, none)}")
    lines.append(f"- **{labels['contracts']}:** {_code_links(module.get('public_symbols', []), prefix, none)}")
    lines.append("")
    return lines


def _port_table(ports: list[dict[str, Any]], labels: dict[str, str]) -> list[str]:
    lines = ["| ID | Owner | Direction | Kind | Timing | Description | Symbols |", "|---|---|---|---|---|---|---|"]
    for port in ports:
        description = port.get("description", {})
        lines.append(
            f"| `{port.get('id')}` | `{port.get('owner')}` | {port.get('direction')} | {port.get('kind')} | "
            f"{description.get('timing')} | {_escape(description.get('purpose', ''))}: {_escape(description.get('data', ''))} | "
            f"{_list_text(port.get('symbols', []), labels['none'])} |"
        )
    return lines


def _event_table(events: list[dict[str, Any]], labels: dict[str, str]) -> list[str]:
    lines = ["| ID | Owner | Delivery | Emitted when | Purpose | Consumers |", "|---|---|---|---|---|---|"]
    for event in events:
        description = event.get("description", {})
        lines.append(
            f"| `{event.get('id')}` | `{event.get('owner')}` | {event.get('delivery')} | "
            f"{_escape(description.get('emitted_when', ''))} | {_escape(description.get('purpose', ''))} | "
            f"{_list_text(description.get('intended_consumers', []), labels['none'])} |"
        )
    return lines


def _flow_view(flow: dict[str, Any], labels: dict[str, str]) -> list[str]:
    lines = [f"### `{flow.get('id')}`", "", _escape(flow.get("description", "")), "", f"#### {labels['flow_diagram']}", "", "```mermaid", "sequenceDiagram"]
    modules = []
    owner = str(flow.get("owner"))
    for value in [owner] + [str(step.get("module")) for step in flow.get("steps", [])]:
        if value not in modules:
            modules.append(value)
    for module_id in modules:
        lines.append(f"    participant {_node_id(module_id)} as {_mermaid_label(module_id)}")
    previous = _node_id(owner)
    for step in flow.get("steps", []):
        current = _node_id(str(step.get("module")))
        lines.append(f"    {previous}->>+{current}: {_mermaid_label(step.get('action', ''))}")
        emitted = step.get("emits", [])
        if emitted:
            lines.append(f"    Note right of {current}: {_mermaid_label(', '.join(str(item) for item in emitted))}")
        lines.append(f"    {current}-->>-{previous}: step {step.get('order')}")
        previous = current
    lines.append("```")
    lines.extend(["", f"#### {labels['steps']}", "", "| # | Module | Action | Receives | Emits | State changes | Side effects |", "|---|---|---|---|---|---|---|"])
    for step in flow.get("steps", []):
        lines.append(
            f"| {step.get('order')} | `{step.get('module')}` | {_escape(step.get('action', ''))} | "
            f"{_list_text(step.get('receives', []), labels['none'])} | {_list_text(step.get('emits', []), labels['none'])} | "
            f"{_escape('; '.join(str(item) for item in step.get('state_changes', [])) or labels['none'])} | "
            f"{_escape('; '.join(str(item) for item in step.get('side_effects', [])) or labels['none'])} |"
        )
    lines.extend(["", f"- **{labels['success']}:** {_escape(flow.get('success', {}).get('result', ''))}"])
    for error in flow.get("errors", []):
        error_ref = error.get("event") or error.get("code")
        lines.append(f"- **{labels['errors']}:** {_escape(error.get('condition'))} → `{_escape(error_ref)}` → {_escape(error.get('handling'))}")
    lines.append("")
    return lines


def render_documents(manifest: dict[str, Any]) -> dict[Path, str]:
    labels = _labels(manifest)
    project = manifest.get("project", {})
    modules = [item for item in manifest.get("modules", []) if isinstance(item, dict)]
    ports = [item for item in manifest.get("ports", []) if isinstance(item, dict)]
    events = [item for item in manifest.get("events", []) if isinstance(item, dict)]
    flows = [item for item in manifest.get("flows", []) if isinstance(item, dict)]
    parents = [module for module in modules if module.get("level") in {"L0", "L1"}]

    index = [GENERATED_MARKER, "", f"# {project.get('name')} {labels['architecture']}", "", f"- Standard: `{manifest.get('standard_version')}`", f"- Schema: `{manifest.get('schema_version')}`", "", f"## {labels['system']}", ""]
    index.extend(_structure_diagram(modules))
    index.extend(["", f"## {labels['parents']}", ""])
    for parent in parents:
        parent_id = str(parent.get("id"))
        index.append(f"- [`{parent_id}`](generated/{_file_name(parent_id)}) — {_escape(parent.get('description', {}).get('purpose', ''))}")
    index.extend(["", f"## {labels['flows']}", ""])
    for flow in flows:
        owner = str(flow.get("owner"))
        index.append(f"- [`{flow.get('id')}`](generated/{_file_name(owner)}#{str(flow.get('id')).replace('.', '')}) — {_escape(flow.get('description', ''))}")
    index.append("")

    system = [GENERATED_MARKER, "", f"# {labels['system']}", ""]
    system.extend(_structure_diagram(modules))
    system.extend(["", f"## {labels['modules']}", ""])
    system.extend(_module_table(modules, labels))
    system.append("")
    for module in modules:
        system.extend(_module_card(module, labels, "../../"))
    system.extend([f"## {labels['ports']}", ""])
    system.extend(_port_table(ports, labels))
    system.extend(["", f"## {labels['event_contracts']}", ""])
    system.extend(_event_table(events, labels))
    system.append("")

    documents: dict[Path, str] = {
        Path("ARCHITECTURE.md"): "\n".join(index),
        Path("generated/system.md"): "\n".join(system),
    }
    for parent in parents:
        parent_id = str(parent.get("id"))
        visible = [parent] + [module for module in modules if module.get("parent") == parent_id]
        visible_ids = {str(module.get("id")) for module in visible}
        page = [GENERATED_MARKER, "", f"# `{parent_id}`", "", f"## {labels['structure']}", ""]
        page.extend(_structure_diagram(visible))
        page.extend(["", f"## {labels['modules']}", ""])
        page.extend(_module_table(visible, labels))
        page.append("")
        for module in visible:
            page.extend(_module_card(module, labels, "../../"))
        selected_ports = [port for port in ports if str(port.get("owner")) in visible_ids]
        selected_events = [event for event in events if str(event.get("owner")) in visible_ids]
        page.extend([f"## {labels['ports']}", ""])
        page.extend(_port_table(selected_ports, labels))
        page.extend(["", f"## {labels['event_contracts']}", ""])
        page.extend(_event_table(selected_events, labels))
        page.extend(["", f"## {labels['flows']}", ""])
        for flow in flows:
            if flow.get("owner") == parent_id:
                page.extend(_flow_view(flow, labels))
        documents[Path("generated") / _file_name(parent_id)] = "\n".join(page)
    return {path: text.rstrip() + "\n" for path, text in documents.items()}


def compare_documents(manifest: dict[str, Any], manifest_path: Path) -> list[tuple[str, str, str]]:
    architecture_root = manifest_path.parent
    expected = render_documents(manifest)
    diagnostics: list[tuple[str, str, str]] = []
    for relative, content in expected.items():
        destination = architecture_root / relative
        if not destination.is_file():
            diagnostics.append(("DOC001", relative.as_posix(), "generated architecture document is missing"))
        elif destination.read_text(encoding="utf-8") != content:
            diagnostics.append(("DOC002", relative.as_posix(), "generated architecture document is stale"))
    generated_root = architecture_root / "generated"
    if generated_root.is_dir():
        for path in generated_root.rglob("*.md"):
            relative = path.relative_to(architecture_root)
            if relative not in expected:
                text = path.read_text(encoding="utf-8", errors="replace")
                if text.startswith(GENERATED_MARKER):
                    diagnostics.append(("DOC003", relative.as_posix(), "obsolete generated architecture document exists"))
    return diagnostics


def write_documents(manifest: dict[str, Any], manifest_path: Path) -> list[Path]:
    architecture_root = manifest_path.parent
    expected = render_documents(manifest)
    for relative in expected:
        destination = architecture_root / relative
        if destination.exists() and not destination.read_text(encoding="utf-8", errors="replace").startswith(GENERATED_MARKER):
            raise FileExistsError(f"refusing to overwrite non-generated document: {destination}")
    written: list[Path] = []
    for relative, content in expected.items():
        destination = architecture_root / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        temporary = destination.with_name(destination.name + ".tmp")
        temporary.write_text(content, encoding="utf-8")
        os.replace(temporary, destination)
        written.append(destination)
    generated_root = architecture_root / "generated"
    if generated_root.is_dir():
        for path in generated_root.rglob("*.md"):
            relative = path.relative_to(architecture_root)
            if relative not in expected:
                text = path.read_text(encoding="utf-8", errors="replace")
                if text.startswith(GENERATED_MARKER):
                    path.unlink()
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", required=True, type=Path)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        manifest = load_manifest(args.manifest)
        if args.write:
            for path in write_documents(manifest, args.manifest):
                print(path)
            return 0
        diagnostics = compare_documents(manifest, args.manifest)
        for rule_id, location, message in diagnostics:
            print(f"MUST {rule_id} {location}: {message}")
        print("PASS" if not diagnostics else "FAIL")
        return 0 if not diagnostics else 1
    except (OSError, ValueError, yaml.YAMLError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
